services:
  api_gateway:
    build: ./services/api_gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  email_parser:
    build: ./services/email_parser
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  linkedin_scraper:
    build: ./services/linkedin_scraper
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  stepstone_parser:
    build: ./services/stepstone_parser
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  telegram_bot:
    build: ./services/telegram_bot
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  chatbot:
    build: ./services/chatbot
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  scheduler:
    build: ./services/scheduler
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
      - RABBITMQ_URL=amqp://guest:guest@192.168.122.100:5672
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  monitoring:
    build: ./services/monitoring
    ports:
      - "3000:3000"  # Grafana
      - "9090:9090"  # Prometheus
    environment:
      - DATABASE_URL=postgresql://jobuser:jobpass@192.168.122.100:5432/jobhunter
      - REDIS_URL=redis://192.168.122.100:6379
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

# Сетевые настройки
networks:
  app-network:
    driver: bridge
